include:
  - ./docker-compose-base.yml

services:
  ragflow:
    depends_on:
      mysql:
        condition: service_healthy
    image: ${RAGFLOW_IMAGE}
    container_name: ragflow-server
    ports:
      - ${SVR_HTTP_PORT}:9380
      - 11080:80
      - 11443:443
    volumes:
      - ${DATA_PATH}/ragflow-logs:/ragflow/logs
      - ./nginx/ragflow.conf:/etc/nginx/conf.d/ragflow.conf
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./Corp-Issuing-CA01-G2.crt:/usr/local/share/ca-certificates/Corp-Issuing-CA01-G2.crt
      - ./ocr-dr.bg.cndc.corpintra.net.crt:/usr/local/share/ca-certificates/ocr-dr.bg.cndc.corpintra.net.crt
      - ./Corp-Root-CA-G2.crt:/usr/local/share/ca-certificates/Corp-Root-CA-G2.crt
    env_file: .env
    command: update-ca-certificates
    environment:
      - TZ=${TIMEZONE}
      - HF_ENDPOINT=${HF_ENDPOINT}
      - MACOS=${MACOS}
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
      - SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
    
    networks:
      - ragflow
    restart: on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"
